change workflow

diff --git a/.github/workflows/s1_agent_download.yml b/.github/workflows/s1_agent_download.yml
--- a/.github/workflows/s1_agent_download.yml
+++ b/.github/workflows/s1_agent_download.yml
@@ -31,7 +31,7 @@ jobs:
       box_distribution: ${{ matrix.boxes.distribution }}
       box_repository: ${{ matrix.boxes.repository }}
       ansible_connection: ${{ matrix.boxes.connection }}
-      ansible_group: ${{ matrix.boxes.connection }}
+      ansible_group: ${{ matrix.boxes.group }}
       display_name: ${{ matrix.boxes.display_name }}
       scenario_name: ${{ matrix.scenario-name }}
       ansible_version: ${{ matrix.versions.ansible }}
@@ -45,17 +45,14 @@ jobs:
             repository: roboxes
             connection: ssh
             display_name: OpenSuse 15
-            group: Linux
           - distribution: rocky8
             repository: roboxes
             connection: ssh
             display_name: Rocky 8
-            group: Linux
           - distribution: ubuntu2204
             repository: roboxes
             connection: ssh
             display_name: Ubuntu 22.04
-            group: Linux
           - distribution: windows-server-2022-standard
             repository: gusztavvargadr
             connection: ssh
@@ -65,7 +62,6 @@ jobs:
             repository: jborean93
             connection: winrm
             display_name: Server 2012r2
-            group: Windows
         scenario-name:
           - default
           - winrm_default
@@ -102,3 +98,32 @@ jobs:
               scenario-name: default,
               versions: { ansible: stable-2.12, python: '3.10' },
             }
+
+  verify-test:
+    needs: call-workflow # run after call-workflow
+    runs-on: [self-hosted, Linux, X64, ansible-collection]
+    if: success() # only run when all call-workflow have passed
+    # store success output flag for assert-passed job
+    outputs:
+      success: ${{ steps.setoutput.outputs.success }}
+    steps:
+      - id: setoutput
+        run: echo "success=true" >> $GITHUB_OUTPUT
+
+  assert-passed:
+    runs-on: [self-hosted, Linux, X64, ansible-collection]
+    if: always() # always run, so we never skip the check
+    needs: [call-workflow, verify-test]
+    steps:
+      # pass step only when output of previous verify-test job is set
+      # in case at least one of the shard fails, verify-test is skipped
+      # and the output will not be set, which will then cause the assert-passed job to fail
+      - run: |
+          passed="${{ needs.verify-test.outputs.success }}"
+          if [[ $passed == "true" ]]; then
+            echo "call-workflow passed"
+            exit 0
+          else
+            echo "call-workflow failed"
+            exit 1
+          fi
